
local function background()
        term.setCursorPos(1,1)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,2)
        term.setBackgroundColor(16384)
        term.clearLine()
        term.setCursorPos(1,3)
        term.setBackgroundColor(256)
        term.clearLine()
        term.setCursorPos(1,4)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,5)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,6)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,7)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,8)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,9)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,10)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,11)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,12)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,13)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,14)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,15)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,16)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,17)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,18)
        term.setBackgroundColor(8)
        term.clearLine()
        term.setCursorPos(1,19)
        term.setBackgroundColor(8)
        term.clearLine()
end

local function background2()
        term.setCursorPos(1,9)
        term.setBackgroundColor(128)
        term.clearLine()
        term.setCursorPos(1,10)
        term.setBackgroundColor(128)
        term.clearLine()
        term.setCursorPos(1,11)
        term.setBackgroundColor(128)
        term.clearLine()


end

background()
background2()